"""Build a distributable single-file `LightStats.exe` via PyInstaller.

Outputs `dist/LightStats.exe` — a standalone Windows executable that
needs no Python installed on the target machine. Resources (icons) are
bundled inside; user data (config.json, history.db, crash.log) lives
next to the .exe, portable-app style.

Usage (from the project root):

    python build.py                 # build once
    python build.py --clean         # wipe build/ and dist/ first
    python build.py --no-upx        # skip UPX compression (smaller step)

Requires PyInstaller: `pip install pyinstaller`. Installs it on demand
if the user said yes via build.bat.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

from ico_builder import build_ico_from_pngs
from version import __version__

HERE = Path(__file__).parent.resolve()
ICONS_DIRS = (HERE / "icon", HERE / "icons")
APP_NAME = "LightStats"
ENTRY_POINT = "main.py"


def _version_tuple() -> tuple[int, int, int, int]:
    """Parse `__version__` (e.g. "1.2.3") into a 4-int VERSIONINFO tuple."""
    parts: list[int] = []
    for chunk in __version__.split("."):
        digits = "".join(ch for ch in chunk if ch.isdigit())
        parts.append(int(digits) if digits else 0)
    parts = (parts + [0, 0, 0, 0])[:4]
    return parts[0], parts[1], parts[2], parts[3]


# ---------------------------------------------------------------------------
# Icon + version file generation
# ---------------------------------------------------------------------------


def _locate_pngs() -> list[Path]:
    for folder in ICONS_DIRS:
        if folder.is_dir():
            pngs = sorted(folder.glob("*.png"))
            if pngs:
                return pngs
    return []


def _synthesize_ico(dest: Path) -> Path | None:
    """Pack the user's PNGs into an .ico. Returns the path, or None if no PNGs."""
    pngs = _locate_pngs()
    if not pngs:
        return None
    data = build_ico_from_pngs(pngs)
    if not data:
        return None
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(data)
    return dest


def _write_version_file(dest: Path, version: tuple[int, int, int, int] | None = None) -> Path:
    if version is None:
        version = _version_tuple()
    """Emit PyInstaller's VSVersionInfo() Python-literal file.

    The string values populate `VERSIONINFO.FileDescription`, which is
    what Task Manager shows next to the process icon — so "LightStats"
    replaces "Python 3.x (Windowed)".
    """
    major, minor, patch, build = version
    version_str = f"{major}.{minor}.{patch}.{build}"
    content = f"""# PyInstaller VSVersionInfo — autogenerated by build.py.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version!r},
    prodvers={version!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904b0',
        [
          StringStruct(u'CompanyName', u'{APP_NAME}'),
          StringStruct(u'FileDescription', u'{APP_NAME}'),
          StringStruct(u'FileVersion', u'{version_str}'),
          StringStruct(u'InternalName', u'{APP_NAME}'),
          StringStruct(u'LegalCopyright', u''),
          StringStruct(u'OriginalFilename', u'{APP_NAME}.exe'),
          StringStruct(u'ProductName', u'{APP_NAME}'),
          StringStruct(u'ProductVersion', u'{version_str}'),
        ],
      ),
    ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])]),
  ],
)
"""
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    return dest


# ---------------------------------------------------------------------------
# PyInstaller invocation
# ---------------------------------------------------------------------------


def _ensure_pyinstaller() -> None:
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("PyInstaller not found — installing…", flush=True)
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "--quiet", "pyinstaller"]
        )


def _run_pyinstaller(
    *,
    entry: Path,
    icon: Path | None,
    version_file: Path | None,
    bundle_dir: Path,
    use_upx: bool,
) -> None:
    cmd: list[str] = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--onefile",
        "--windowed",
        "--name", APP_NAME,
        "--distpath", str(bundle_dir / "dist"),
        "--workpath", str(bundle_dir / "build"),
        "--specpath", str(bundle_dir),
        "--clean",
    ]
    if icon is not None:
        cmd += ["--icon", str(icon)]
    if version_file is not None:
        cmd += ["--version-file", str(version_file)]
    if not use_upx:
        cmd += ["--noupx"]

    # Bundle icons folder so icon_loader can still pick user-set icons at
    # runtime (extracted to sys._MEIPASS). Windows uses `;` as the path
    # separator in --add-data. "SRC;DEST_INSIDE_BUNDLE".
    for folder in ICONS_DIRS:
        if folder.is_dir():
            cmd += ["--add-data", f"{folder};{folder.name}"]
            break

    # Hidden imports for modules that get resolved at runtime by name:
    # - pynvml is installed as nvidia-ml-py; `import pynvml` works but
    #   PyInstaller's dep graph can miss the NVML DLL shim it ships with.
    # - pyqtgraph loads its drawing backends lazily.
    hidden = ["pynvml", "pyqtgraph.graphicsItems.ViewBox.ViewBoxMenu"]
    for mod in hidden:
        cmd += ["--hidden-import", mod]

    cmd.append(str(entry))
    print("Running:", " ".join(cmd), flush=True)
    subprocess.check_call(cmd)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description="Build LightStats.exe.")
    parser.add_argument("--clean", action="store_true", help="Wipe build/ and dist/ first.")
    parser.add_argument("--no-upx", action="store_true", help="Skip UPX compression.")
    args = parser.parse_args()

    bundle_dir = HERE / "_build_cache"  # PyInstaller scratch + output home
    dist_dir = bundle_dir / "dist"

    if args.clean:
        for victim in (bundle_dir,):
            if victim.exists():
                print(f"Removing {victim} …", flush=True)
                shutil.rmtree(victim, ignore_errors=True)

    _ensure_pyinstaller()

    ico = _synthesize_ico(bundle_dir / "app.ico")
    if ico is None:
        print(
            "No .png icons found in icon/ or icons/ — the build will use "
            "the default PyInstaller icon.",
            file=sys.stderr,
        )
    else:
        print(f"Built icon: {ico}", flush=True)

    version_file = _write_version_file(bundle_dir / "version_info.txt")
    print(f"Version file: {version_file}", flush=True)

    _run_pyinstaller(
        entry=HERE / ENTRY_POINT,
        icon=ico,
        version_file=version_file,
        bundle_dir=bundle_dir,
        use_upx=not args.no_upx,
    )

    final_exe = dist_dir / f"{APP_NAME}.exe"
    if not final_exe.exists():
        print(f"Build finished but {final_exe} is missing — check PyInstaller output.",
              file=sys.stderr)
        return 1

    # Copy the final .exe up to a predictable top-level `dist/` so the
    # user doesn't have to dig into _build_cache/.
    public_dist = HERE / "dist"
    public_dist.mkdir(exist_ok=True)
    target = public_dist / final_exe.name
    shutil.copy2(final_exe, target)
    print(f"\nBuilt: {target}  ({target.stat().st_size / 1024 / 1024:.1f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
